# Generated by Django 5.2.5 on 2025-08-26 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_logo_user_avatar_kiosk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_backgrounds/', verbose_name='Imagen de Fondo'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
