# Generated by Django 5.2.5 on 2025-08-26 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticketcategory_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsubcategory',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_backgrounds/', verbose_name='Imagen de Fondo'),
        ),
        migrations.AddField(
            model_name='ticketsubcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticketsubcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketsubcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
