# Generated by Django 5.2.5 on 2025-08-27 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticketsubcategory_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.ticketsubcategory'),
        ),
    ]
